-- Table: public.stock_temporal

-- DROP TABLE IF EXISTS public.stock_temporal;

CREATE TABLE IF NOT EXISTS public.stock_temporal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    end_validity date,
    quantity integer,
    start_validity date,
    film_id bigint,
    CONSTRAINT stock_temporal_pkey PRIMARY KEY (id),
    CONSTRAINT fkimrk4ulx4pno9u0nm9pdjom7v FOREIGN KEY (film_id)
        REFERENCES public.dim_film (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.stock_temporal
    OWNER to postgres;