-- Table: public.price_temporal

-- DROP TABLE IF EXISTS public.price_temporal;

CREATE TABLE IF NOT EXISTS public.price_temporal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    end_validity date,
    price double precision,
    start_validity date,
    film_id bigint,
    CONSTRAINT price_temporal_pkey PRIMARY KEY (id),
    CONSTRAINT fkh8omvf8kdlhpgw431h2jji0ke FOREIGN KEY (film_id)
        REFERENCES public.dim_film (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.price_temporal
    OWNER to postgres;