-- Table: public.dim_film

-- DROP TABLE IF EXISTS public.dim_film;

CREATE TABLE IF NOT EXISTS public.dim_film
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    duration integer,
    genre character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT dim_film_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.dim_film
    OWNER to postgres;