-- Table: public.fact_rental

-- DROP TABLE IF EXISTS public.fact_rental;

CREATE TABLE IF NOT EXISTS public.fact_rental
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    paidvalue double precision,
    quantity integer,
    client_id bigint,
    film_id bigint,
    store_id bigint,
    time_id bigint,
    CONSTRAINT fact_rental_pkey PRIMARY KEY (id),
    CONSTRAINT fk29eaxv032f4x6r93o7bbmowor FOREIGN KEY (film_id)
        REFERENCES public.dim_film (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk9ek16u16s7rd92qyme5asnt4l FOREIGN KEY (time_id)
        REFERENCES public.dim_time (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkkdvvv6mk8x9ofrkwp3rnsj4gm FOREIGN KEY (store_id)
        REFERENCES public.dim_store (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkrx1cwfnv1ctxiswf8w5sri4ya FOREIGN KEY (client_id)
        REFERENCES public.dim_client (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.fact_rental
    OWNER to postgres;