-- Table: public.dim_time

-- DROP TABLE IF EXISTS public.dim_time;

CREATE TABLE IF NOT EXISTS public.dim_time
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date,
    day integer,
    month integer,
    year integer,
    CONSTRAINT dim_time_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.dim_time
    OWNER to postgres;